---
- name: Set up the requested lab on the Cribl leader.
  hosts: "tag_Name_Leader_{{student}}_Box"
  remote_user: ec2-user
  become: yes
  vars_files:
    - terraform_outputs.yaml 
  vars:
    ansible_ssh_private_key_file: temp.pem
  tasks:
    - block:
        - name: Create the local cribl user
          ansible.builtin.user:
            name: cribl
            home: /home/cribl
        - name: Install the lastest version of Cribl
          ansible.builtin.unarchive:
            src: "{{ lookup('ansible.builtin.url', 'https://cdn.cribl.io/dl/latest-arm64') }}" 
            dest: /opt
            remote_src: yes
            exclude: ['._*']
        - name: Set ownership on the cribl directory
          ansible.builtin.file:
            path: /opt/cribl
            owner: cribl
            group: cribl
            recurse: yes
            state: directory
        - name: Install git on the leader node
          ansible.builtin.yum:
            name: git
            state: latest
        - name: Set Cribl to start on reboot
          ansible.builtin.command:
            cmd: /opt/cribl/bin/cribl boot-start enable -u cribl
        - name: Create the Ansible facts directory
          ansible.builtin.file:
            path: /etc/ansible/facts.d/
            state: directory
      when: breakingpoint > 0  and ansible_local['cribl']['cribl']['breakingpoint'] is undefined
    - block:
        - name: Download Cribl breaking point settings
          amazon.aws.aws_s3:
            bucket: "{{aws_s3_bucket}}"
            object: leader/breakingpoint-{{breakingpoint}}.tar
            dest: /tmp/breakingpoint-{{breakingpoint}}.tar
            profile: "{{aws_profile}}"
            mode: get
          delegate_to: 127.0.0.1
          become: false
        - name: Copy downloaded settings to the leader box
          ansible.builtin.copy:
            src: /tmp/breakingpoint-{{breakingpoint}}.tar
            dest: /tmp/breakingpoint-{{breakingpoint}}.tar
        - name: Apply the updated changes to leader node.
          ansible.builtin.unarchive:
            src: /tmp/breakingpoint-{{breakingpoint}}.tar
            dest: /opt/cribl
      when: breakingpoint > 1
    - block:
        - name: Download Outputs File
          amazon.aws.aws_s3:
            bucket: "{{aws_s3_bucket}}"
            object: leader/bp-14-output.yaml.j2
            dest: /tmp/output.yaml.j2
            profile: "{{aws_profile}}"
            mode: get
          delegate_to: 127.0.0.1
          become: false
        - name: Set up outputs config file for datacenter group
          ansible.builtin.template:
            src: /tmp/output.yaml.j2
            dest: /opt/cribl/groups/datacenter_us/local/cribl/outputs.yml
      when: breakingpoint > 14 and breakingpoint < 34
    - block:
        - name: Download Outputs File
          amazon.aws.aws_s3:
            bucket: "{{aws_s3_bucket}}"
            object: leader/bp-22-output.yaml.j2
            dest: /tmp/output.yaml.j2
            profile: "{{aws_profile}}"
            mode: get
          delegate_to: 127.0.0.1
          become: false
        - name: Set up outputs config file for datacenter group
          ansible.builtin.template:
            src: /tmp/output.yaml.j2
            dest: /opt/cribl/groups/datacenter_us/local/cribl/outputs.yml
      when: breakingpoint > 33 and breakingpoint < 40 
    - name: Set ownership on the cribl directory again
      ansible.builtin.file:
        path: /opt/cribl
        owner: cribl
        group: cribl
        recurse: yes
        state: directory
    - name: Update the facts file with the breaking point
      community.general.ini_file:
         path: /etc/ansible/facts.d/cribl.fact
         section: cribl
         option: breakingpoint
         value: "{{breakingpoint}}"
    - name: Start the Cribl service
      ansible.builtin.systemd:
         name: cribl
         state: restarted
    - name: Push config to worker groups
      ansible.builtin.command: "{{ item }}"
      with_items:
        - /opt/cribl/bin/cribl auth login
        - /opt/cribl/bin/cribl git commit-deploy -g datacenter_us
        - /opt/cribl/bin/cribl git commit-deploy -g default 
      become: yes
      become_user: cribl
      environment:
        CRIBL_USERNAME: admin
        CRIBL_PASSWORD: cr1bluser
        CRIBL_HOST: https://localhost:9000
      when: breakingpoint > 8


- name: Set up the requested lab on the Cribl worker.
  hosts: "tag_Name_Worker_{{student}}_Box"
  remote_user: ec2-user
  become: yes
  vars_files:
    - terraform_outputs.yaml 
  vars:
    ansible_ssh_private_key_file: temp.pem
  tasks:
    - name: Create the Ansible facts directory
      ansible.builtin.file:
        path: /etc/ansible/facts.d/
        state: directory
    - name: Set a presistent ansible fact for the breaking point
      community.general.ini_file:
        path: /etc/ansible/facts.d/cribl.fact
        section: cribl
        option: breakingpoint
        value: "{{breakingpoint}}"
    - name: Update Ansible facts information
      setup:
    - block:
        - name: Copy up the worker bootstrap script
          ansible.builtin.template:
            src: install_worker.sh.j2
            dest: /tmp/install_worker.sh
            mode: 0700
        - name: Run the bootstrap script
          ansible.builtin.command:
            cmd: /tmp/install_worker.sh
        - name: Set bootstrap check bit
          community.general.ini_file:
            path: /etc/ansible/facts.d/cribl.fact
            section: cribl
            option: bootstrap
            value: yes
      when: breakingpoint > 9 and ansible_local['cribl']['cribl']['bootstrap'] is undefined 


- name: Set up the requested lab on the Cribl Everthing Box..
  hosts: "tag_Name_Everything_{{student}}_Box"
  remote_user: ec2-user
  become: yes
  vars_files:
    - terraform_outputs.yaml 
  vars:
    ansible_ssh_private_key_file: temp.pem
  tasks:
    - name: Configure Splunk Indexes
      ansible.builtin.command: "terraform -chdir=splunk apply -var=everything_splunk={{ everythingbox_ip }} -auto-approve"
      become: no
      delegate_to: 127.0.0.1
      when: breakingpoint > 12
    - block:
        - name: Get the data gen config file
          amazon.aws.aws_s3:
            bucket: "{{aws_s3_bucket}}"
            object: everythingbox/inputs-15.yml
            dest: /tmp/inputs.yml
            profile: "{{aws_profile}}"
            mode: get
          delegate_to: 127.0.0.1
          become: false
        - name: Copy up the data gen file
          ansible.builtin.copy:
            src: /tmp/inputs.yml
            dest: /opt/cribl/local/cribl/inputs.yml
            owner: cribl
            group: cribl
        - name: Restart datagen instance to pick up the changes
          systemd:
            name: cribl
            state: restarted
      when: breakingpoint > 14 and breakingpoint < 22
    - block:
        - name: Get the data gen config file
          amazon.aws.aws_s3:
            bucket: "{{aws_s3_bucket}}"
            object: everythingbox/inputs-22.yml
            dest: /tmp/inputs.yml
            profile: "{{aws_profile}}"
            mode: get
          delegate_to: 127.0.0.1
          become: false
        - name: Copy up the data gen file
          ansible.builtin.copy:
            src: /tmp/inputs.yml
            dest: /opt/cribl/local/cribl/inputs.yml
            owner: cribl
            group: cribl
        - name: Restart datagen instance to pick up the changes
          systemd:
            name: cribl
            state: restarted
      when: breakingpoint > 21  and breakingpoint <= 30 


...
