output "ssh_key" {
  value     = tls_private_key.ssh_key.private_key_pem
  sensitive = true
}

output "ec2_everything_box_ip" {
  value = aws_instance.everything_box.public_ip
}

output "ec2_leader" {
  value = ["${aws_instance.leader.*.public_ip}"]
}

output "ec2_worker" {
  value = ["${aws_instance.worker.*.public_ip}"]
}

resource "local_file" "tf_ansible_vars_file_new" {
  content = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.

    aws_s3_bucket: ${var.aws_s3_bucket}
    everythingbox_ip: ${aws_instance.everything_box.public_ip}
    leaderbox_ip: ${aws_instance.leader.public_ip}
    workerbox_ip: ${aws_instance.worker.public_ip}
    DOC
  filename = "./terraform_outputs.yaml"
}